import './globals.css'
import { Inter } from 'next/font/google'
import { Children } from "./Types"
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Procrastinate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Children ) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Analytics/>
      </body>
    </html>
  )
}
